### ISSUE TITLE
How can I validate a recovery code?

### ISSUE THREAD

**Issue by realtebo** [antonioribeiro/recovery#9]
To me is not clear the workflow of using recovery codes.

Must I generate recovery codes and save it in db, related to the user?

Then If user loose access, I must simply ask a recovery code and the if it's in db then re-show the original qr (or a different one to invalidate the previous one)?

**Comment by TechTailor** [comment]
The process is simple. You add an additional column to the user's table say "recovery_codes" and store the codes generated in it. 

The workflow of using it depends on you, there are different best practices, I would recommend you just do what you personally would feel best.
Ex: Say a user loses access to their phone, so now they are stuck at the login page, you can ask for a recovery code and then authenticate the user into your app (at this point its up to you if you want to automatically disable 2fa and generate a new secret and ask user to setup again or just allow the user to use the app as usual). 

In case you want to reset, just delete the data in the "recovery_codes" column and re-generate the secret.

Everytime you regenerate the secret, besure to clear out the previous codes.

Hope this helps.

PS> You can totally ignore the concept of recovery codes itself if don't want the hassle of it.

-TT

**Comment by antonioribeiro** [comment]
This package is really only about generating the codes, how you validate then is up to you. If you need help with Laravel development, their [Discord server](https://discord.com/invite/mPZNm7A) is a good support channel.

**Comment by realtebo** [comment]
Thanks 

I supposed recovery codes was special TOTP able to pass be verified in any time windows.
I understand now that is a tool to bypass TOTP to allow user to a automated recovery.
